AllCops:
  Include:
    - Gemfile
    - Guardfile
    - Rakefile
    - fetching.gemspec
    - rubocop-rspec

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/Documentation:
  Enabled: false

Style/RegexpLiteral:
  Exclude:
    - Guardfile
