language: ruby
script:
  - bundle exec rspec
  - bundle exec rubocop --display-cop-names
sudo: false
rvm:
  - ruby-1.9.3-p551
  - ruby-2.0.0-p648
  - ruby-2.1.10
  - ruby-2.2.7
  - ruby-2.3.4
  - ruby-2.4.1
  - jruby-9.1.5.0
